matrix:
    include:
        - language: go
          go:
              - 1.x
          before_script:
              - cd go/regions
        - language: node_js
          node_js:
              - 11
              - 10
              - 9
              - 8
              - 7
              - 6
          before_script:
              - cd javascript
